// _FileTypeSelector_EOArchive.java
// Generated by EnterpriseObjects palette at 2005\u5e7411\u670819\u65e5\u571f\u66dc\u65e5 11\u664241\u520620\u79d2Japan

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _FileTypeSelector_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOView _nsCustomView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1;

    public _FileTypeSelector_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "xmlRadio")) != null)) {
            _jRadioButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton1");
        } else {
            _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("XML"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "matrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 2, 4, 2), "NSMatrix1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addPanel")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "csvRadio")) != null)) {
            _jRadioButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton0");
        } else {
            _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("CSV"), "");
        }
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "matrix");
        }

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _connect(_owner(), _jRadioButton1, "xmlRadio");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "addPanel");
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _connect(_owner(), _jRadioButton0, "csvRadio");
        }
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _setFontForComponent(_jRadioButton1, "Hiragino Kaku Gothic Pro", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton1.setSize(77, 18);
            _jRadioButton1.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton1);
            _jRadioButton0.setSize(77, 18);
            _jRadioButton0.setLocation(81, 0);
            _nsMatrix0.add(_jRadioButton0);
            _setFontForComponent(_nsMatrix0, "Hiragino Kaku Gothic Pro", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsMatrix0.setSize(158, 18);
            _nsMatrix0.setLocation(81, 7);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsMatrix0);
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _setFontForComponent(_jRadioButton0, "Hiragino Kaku Gothic Pro", 13, Font.PLAIN);
        }
    }
}
