/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkColorMaterialHelper_vs string.
 *
 */
#ifndef __vtkColorMaterialHelper_vs_h
#define __vtkColorMaterialHelper_vs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkColorMaterialHelper_vs;

#endif /* #ifndef __vtkColorMaterialHelper_vs_h */
