/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkDepthPeeling_fs string.
 *
 */
#ifndef __vtkDepthPeeling_fs_h
#define __vtkDepthPeeling_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkDepthPeeling_fs;

#endif /* #ifndef __vtkDepthPeeling_fs_h */
