/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveNoCroppingFS_h */
