/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h
#define __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_PerspectiveProjectionFS_h */
