/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPNoCroppingFS_h */
