/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFS_h */
