/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveFS_h */
