/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPBinaryMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPBinaryMaskFS_h
#define __vtkGPUVolumeRayCastMapper_MIPBinaryMaskFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPBinaryMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPBinaryMaskFS_h */
