/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h */
