/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h */
