/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeMaskFS_h */
