/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentCroppingFS_h */
