/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPFourDependentFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPFourDependentFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPFourDependentFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPFourDependentFS_h */
