/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h */
