/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_OneComponentFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_OneComponentFS_h
#define __vtkGPUVolumeRayCastMapper_OneComponentFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_OneComponentFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_OneComponentFS_h */
