/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_FourComponentsFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_FourComponentsFS_h
#define __vtkGPUVolumeRayCastMapper_FourComponentsFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_FourComponentsFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_FourComponentsFS_h */
