/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ScaleBiasFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h
#define __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ScaleBiasFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ScaleBiasFS_h */
