/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ParallelProjectionFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h
#define __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ParallelProjectionFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ParallelProjectionFS_h */
