/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPNoCroppingFS_h */
