/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentCroppingFS_h */
