/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_NoShadeFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_NoShadeFS_h
#define __vtkGPUVolumeRayCastMapper_NoShadeFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_NoShadeFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_NoShadeFS_h */
