/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkGPUVolumeRayCastMapper_ShadeFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_ShadeFS_h
#define __vtkGPUVolumeRayCastMapper_ShadeFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_ShadeFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_ShadeFS_h */
