/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkHAVSVolumeMapper_kbufferVP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_kbufferVP_h
#define __vtkHAVSVolumeMapper_kbufferVP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkHAVSVolumeMapper_kbufferVP;

#endif /* #ifndef __vtkHAVSVolumeMapper_kbufferVP_h */
