/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkHAVSVolumeMapper_k6BeginFP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k6BeginFP_h
#define __vtkHAVSVolumeMapper_k6BeginFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkHAVSVolumeMapper_k6BeginFP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k6BeginFP_h */
