/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkLineIntegralConvolution2D_fs2 string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_fs2_h
#define __vtkLineIntegralConvolution2D_fs2_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkLineIntegralConvolution2D_fs2;

#endif /* #ifndef __vtkLineIntegralConvolution2D_fs2_h */
