/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkLineIntegralConvolution2D_fs1 string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_fs1_h
#define __vtkLineIntegralConvolution2D_fs1_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkLineIntegralConvolution2D_fs1;

#endif /* #ifndef __vtkLineIntegralConvolution2D_fs1_h */
