// Loadable shader code
//
// Generated by ../../bin/ProcessShader
//
#ifndef __vtkMaterial_h
#define __vtkMaterial_h


// From file /Users/antoinerosset/VTK/Utilities/MaterialLibrary/Materials/GLSLTwisted.xml
static const char* vtkMaterialGLSLTwistedXML0 =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<Material name=\"Twisted\">\n"
"  <Property name=\"Property1\">\n"
"    <Member name=\"DiffuseColor\" number_of_elements=\"3\" type=\"Double\" value=\"1.0 0.5 0.5\" />\n"
"  </Property>\n"
"\n"
"  <Shader scope=\"Vertex\" name=\"GLSLTwisted\" location=\"Library\" \n"
"    language=\"GLSL\" entry=\"main\">\n"
"    <ApplicationUniform name=\"Rate\" value=\"Rate\"> </ApplicationUniform>\n"
"  </Shader>\n"
"  <!--\n"
"  <Shader scope=\"Fragment\" name=\"GLSLTwisted\" location=\"c:/temp/GLSLTwistedFrag.glsl\" language=\"GLSL\" entry=\"main\">\n"
"  </Shader>\n"
"    -->\n"
"</Material>\n"
"\n";
// Get single string
char* vtkMaterialGLSLTwistedGetXML()
{
  int len = ( 0
    + static_cast<int>(strlen(vtkMaterialGLSLTwistedXML0)) );
  char* res = new char[ len + 1];
  res[0] = 0;
  strcat(res, vtkMaterialGLSLTwistedXML0);
  return res;
}



#endif
