/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkOpenGLPropertyDefaultMain_fs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultMain_fs_h
#define __vtkOpenGLPropertyDefaultMain_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkOpenGLPropertyDefaultMain_fs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultMain_fs_h */
