/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkOpenGLPropertyDefaultPropFunc_fs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h
#define __vtkOpenGLPropertyDefaultPropFunc_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkOpenGLPropertyDefaultPropFunc_fs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h */
