/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkOpenGLPropertyDefaultPropFunc_vs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultPropFunc_vs_h
#define __vtkOpenGLPropertyDefaultPropFunc_vs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkOpenGLPropertyDefaultPropFunc_vs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultPropFunc_vs_h */
