/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkProjectedAAHexahedraMapper_VS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_VS_h
#define __vtkProjectedAAHexahedraMapper_VS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkProjectedAAHexahedraMapper_VS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_VS_h */
