/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkProjectedAAHexahedraMapper_GS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_GS_h
#define __vtkProjectedAAHexahedraMapper_GS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkProjectedAAHexahedraMapper_GS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_GS_h */
