/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkProjectedAAHexahedraMapper_FS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_FS_h
#define __vtkProjectedAAHexahedraMapper_FS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkProjectedAAHexahedraMapper_FS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_FS_h */
