/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkSurfaceLICPainter_vs1 string.
 *
 */
#ifndef __vtkSurfaceLICPainter_vs1_h
#define __vtkSurfaceLICPainter_vs1_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkSurfaceLICPainter_vs1;

#endif /* #ifndef __vtkSurfaceLICPainter_vs1_h */
