/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkSurfaceLICPainter_fs2 string.
 *
 */
#ifndef __vtkSurfaceLICPainter_fs2_h
#define __vtkSurfaceLICPainter_fs2_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkSurfaceLICPainter_fs2;

#endif /* #ifndef __vtkSurfaceLICPainter_fs2_h */
