/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkSurfaceLICPainter_fs1 string.
 *
 */
#ifndef __vtkSurfaceLICPainter_fs1_h
#define __vtkSurfaceLICPainter_fs1_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkSurfaceLICPainter_fs1;

#endif /* #ifndef __vtkSurfaceLICPainter_fs1_h */
