/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkStructuredGridLIC2D_fs string.
 *
 */
#ifndef __vtkStructuredGridLIC2D_fs_h
#define __vtkStructuredGridLIC2D_fs_h

#include "vtkSystemIncludes.h"

VTK_HYBRID_EXPORT extern const char *vtkStructuredGridLIC2D_fs;

#endif /* #ifndef __vtkStructuredGridLIC2D_fs_h */
