/* DO NOT EDIT.
 * Generated by ../bin/vtkEncodeString
 * 
 * Declare the vtkVolumeTextureMapper3D_OneComponentShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_OneComponentShadeFP_h
#define __vtkVolumeTextureMapper3D_OneComponentShadeFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkVolumeTextureMapper3D_OneComponentShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_OneComponentShadeFP_h */
