// _MIRCXMLEditor_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, September 6, 2005 12:15:35 PM America/Denver

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MIRCXMLEditor_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ArrayController _arrayController0, _arrayController1, _arrayController2, _arrayController3;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector12, _iBHelpConnector13, _iBHelpConnector14, _iBHelpConnector2, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    ImageCell _imageCell0;
    ObjectController _objectController0;
    QTMovieView _nsCustomView0, _nsCustomView1;
    com.webobjects.eointerface.swing.EOForm _nsForm0;
    com.webobjects.eointerface.swing.EOFormCell _eoFormCell0, _eoFormCell1, _eoFormCell2;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2, _nsTableView3;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn11, _eoTableColumn12, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0, _nsTextView1, _nsTextView2, _nsTextView3, _nsTextView4;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox10, _nsBox11, _nsBox12, _nsBox13, _nsBox14, _nsBox15, _nsBox16, _nsBox17, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsBox8, _nsBox9, _nsSegmentedControl0, _nsSegmentedControl1, _nsView0, _nsView1, _nsView2, _nsView3, _nsView4;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6;
    javax.swing.JPanel _nsView5;
    javax.swing.JTabbedPane _nsTabView0;

    public _MIRCXMLEditor_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _arrayController3 = (ArrayController)_registered(new ArrayController(), "ThumbnailController");
        _objectController0 = (ObjectController)_registered(new ObjectController(), "patientController");
        _imageCell0 = (ImageCell)_registered(new ImageCell(), "");
        _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Edit XML"), "NSButton1");
        _eoTableColumn12 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView3 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsView4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox17 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox16 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox15 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox14 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox13 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox12 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _iBHelpConnector14 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector13 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextView4 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextView3 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsBox11 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox10 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBHelpConnector12 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _eoTableColumn11 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextView2 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _eoFormCell2 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        _eoFormCell1 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        _eoFormCell0 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        _nsForm0 = (com.webobjects.eointerface.swing.EOForm)_registered(new com.webobjects.eointerface.swing.EOForm(3, 1, 1, 8), "NSForm1");
        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox2");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField31");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Choose"), "NSButton");
        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Capture Video"), "NSButton");
        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("Capture Video"), "NSButton");
        _nsSegmentedControl1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        _nsSegmentedControl0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Save"), "NSButton");
        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "discussionMovieView")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (QTMovieView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (QTMovieView)_registered(new QTMovieView(), "View");
        }

        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "historyMovieView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (QTMovieView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (QTMovieView)_registered(new QTMovieView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "imageArrayController")) != null)) {
            _arrayController2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController2");
        } else {
            _arrayController2 = (ArrayController)_registered(new ArrayController(), "imageArrayController");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "questionArrayController")) != null)) {
            _arrayController1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController1");
        } else {
            _arrayController1 = (ArrayController)_registered(new ArrayController(), "QuestionController");
        }

        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Delete"), "NSButton1");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "NSButton");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "authorController")) != null)) {
            _arrayController0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController0");
        } else {
            _arrayController0 = (ArrayController)_registered(new ArrayController(), "AuthorController");
        }

        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextView1 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "authorController.tableView")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView5 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseRefDoc", _nsButton5), ""));
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "captureDiscussion", _nsButton4), ""));
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "captureHistory", _nsButton3), ""));
        _nsSegmentedControl1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "imageAction", _nsSegmentedControl1), ""));
        _nsSegmentedControl0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "quizAction", _nsSegmentedControl0), ""));
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "save", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "discussionMovieView");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "historyMovieView");
        }

        if (_replacedObjects.objectForKey("_arrayController2") == null) {
            _connect(_owner(), _arrayController2, "imageArrayController");
        }

        if (_replacedObjects.objectForKey("_arrayController1") == null) {
            _connect(_owner(), _arrayController1, "questionArrayController");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_arrayController0") == null) {
            _connect(_owner(), _arrayController0, "authorController");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        _eoTableColumn12.setMinWidth(59);
        _eoTableColumn12.setMaxWidth(1000);
        _eoTableColumn12.setPreferredWidth(741);
        _eoTableColumn12.setWidth(741);
        _eoTableColumn12.setResizable(true);
        _eoTableColumn12.setHeaderValue("Question");
        _nsTableView3.table().addColumn(_eoTableColumn12);
        _setFontForComponent(_nsTableView3.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView3.table().setRowHeight(20);
        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsTableView3.setSize(762, 95);
        _nsTableView3.setLocation(20, 20);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTableView3, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsTableView3);
        _nsSegmentedControl0.setSize(263, 24);
        _nsSegmentedControl0.setLocation(521, 122);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsSegmentedControl0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsSegmentedControl0);
        if (!(_nsBox17.getLayout() instanceof EOViewLayout)) { _nsBox17.setLayout(new EOViewLayout()); }
        _nsTextView4.setSize(751, 193);
        _nsTextView4.setLocation(16, 14);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsTextView4, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox17.add(_nsTextView4);
        _nsButton4.setSize(123, 26);
        _nsButton4.setLocation(443, 486);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox17.add(_nsButton4);
        _nsCustomView1.setSize(302, 265);
        _nsCustomView1.setLocation(260, 215);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsBox17.add(_nsCustomView1);
        if (!(_nsBox16.getLayout() instanceof EOViewLayout)) { _nsBox16.setLayout(new EOViewLayout()); }
        _nsBox17.setSize(783, 519);
        _nsBox17.setLocation(2, 15);
        ((EOViewLayout)_nsBox16.getLayout()).setAutosizingMask(_nsBox17, EOViewLayout.MinYMargin);
        _nsBox16.add(_nsBox17);
        _nsBox16.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Discussion", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox15.getLayout() instanceof EOViewLayout)) { _nsBox15.setLayout(new EOViewLayout()); }
        _nsTextView3.setSize(751, 58);
        _nsTextView3.setLocation(16, 17);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsTextView3, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox15.add(_nsTextView3);
        if (!(_nsBox14.getLayout() instanceof EOViewLayout)) { _nsBox14.setLayout(new EOViewLayout()); }
        _nsBox15.setSize(783, 86);
        _nsBox15.setLocation(2, 15);
        ((EOViewLayout)_nsBox14.getLayout()).setAutosizingMask(_nsBox15, EOViewLayout.MinYMargin);
        _nsBox14.add(_nsBox15);
        _nsBox14.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Findings", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox13.getLayout() instanceof EOViewLayout)) { _nsBox13.setLayout(new EOViewLayout()); }
        _nsTextField9.setSize(743, 22);
        _nsTextField9.setLocation(21, 11);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox13.add(_nsTextField9);
        if (!(_nsBox12.getLayout() instanceof EOViewLayout)) { _nsBox12.setLayout(new EOViewLayout()); }
        _nsBox13.setSize(783, 53);
        _nsBox13.setLocation(2, 15);
        ((EOViewLayout)_nsBox12.getLayout()).setAutosizingMask(_nsBox13, EOViewLayout.MinYMargin);
        _nsBox12.add(_nsBox13);
        _nsBox12.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Differential Diagnosis", true, "Lucida Grande", 11, Font.PLAIN));
        _nsTextView4.setEditable(true);
        _nsTextView4.setOpaque(true);
        _nsTextView4.setText("");
        _connect(_nsTextField9, _nsTextView4, "nextFocusableComponent");
        _setFontForComponent(_nsTextField9, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField9.setEditable(true);
        _nsTextField9.setOpaque(true);
        _nsTextField9.setText("");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField9.setSelectable(true);
        _nsTextField9.setEnabled(true);
        _connect(_nsTextView3, _nsTextField9, "nextFocusableComponent");
        _nsTextView3.setEditable(true);
        _nsTextView3.setOpaque(true);
        _nsTextView3.setText("");
        _connect(_nsTextField8, _nsTextView3, "nextFocusableComponent");
        _setFontForComponent(_nsTextField8, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField8.setEditable(true);
        _nsTextField8.setOpaque(true);
        _nsTextField8.setText("");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField8.setSelectable(true);
        _nsTextField8.setEnabled(true);
        if (!(_nsBox11.getLayout() instanceof EOViewLayout)) { _nsBox11.setLayout(new EOViewLayout()); }
        _nsTextField8.setSize(743, 22);
        _nsTextField8.setLocation(21, 6);
        ((EOViewLayout)_nsBox11.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox11.add(_nsTextField8);
        if (!(_nsBox10.getLayout() instanceof EOViewLayout)) { _nsBox10.setLayout(new EOViewLayout()); }
        _nsBox11.setSize(783, 34);
        _nsBox11.setLocation(2, 15);
        ((EOViewLayout)_nsBox10.getLayout()).setAutosizingMask(_nsBox11, EOViewLayout.MinYMargin);
        _nsBox10.add(_nsBox11);
        _nsBox10.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Diagnosis", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsBox10.setSize(787, 51);
        _nsBox10.setLocation(17, 4);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox10, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsBox10);
        _nsBox12.setSize(787, 70);
        _nsBox12.setLocation(17, 160);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox12, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsBox12);
        _nsBox14.setSize(787, 103);
        _nsBox14.setLocation(17, 53);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox14, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsBox14);
        _nsBox16.setSize(787, 536);
        _nsBox16.setLocation(17, 234);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox16, EOViewLayout.MinXMargin | EOViewLayout.WidthSizable | EOViewLayout.HeightSizable | EOViewLayout.MinYMargin);
        _nsView3.add(_nsBox16);
        _eoTableColumn11.setMinWidth(27);
        _eoTableColumn11.setMaxWidth(1000);
        _eoTableColumn11.setPreferredWidth(97);
        _eoTableColumn11.setWidth(97);
        _eoTableColumn11.setResizable(true);
        _eoTableColumn11.setHeaderValue("Title");
        if ((_eoTableColumn11.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn11.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn10.setMinWidth(46);
        _eoTableColumn10.setMaxWidth(1000);
        _eoTableColumn10.setPreferredWidth(109);
        _eoTableColumn10.setWidth(109);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("Images");
        _nsTableView2.table().addColumn(_eoTableColumn10);
        _nsTableView2.table().addColumn(_eoTableColumn11);
        _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView2.table().setRowHeight(67);
        _eoTableColumn9.setMinWidth(59);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(128);
        _eoTableColumn9.setWidth(128);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("Annotated");
        if ((_eoTableColumn9.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn9.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn8.setMinWidth(10);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(162);
        _eoTableColumn8.setWidth(162);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Original");
        if ((_eoTableColumn8.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn8.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn7.setMinWidth(40);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(139);
        _eoTableColumn7.setWidth(139);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Full Size");
        if ((_eoTableColumn7.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn7.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn6.setMinWidth(40);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(99);
        _eoTableColumn6.setWidth(99);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Thumbnail");
        if ((_eoTableColumn6.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn6.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView1.table().addColumn(_eoTableColumn6);
        _nsTableView1.table().addColumn(_eoTableColumn7);
        _nsTableView1.table().addColumn(_eoTableColumn8);
        _nsTableView1.table().addColumn(_eoTableColumn9);
        _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView1.table().setRowHeight(21);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTableView1.setSize(557, 706);
        _nsTableView1.setLocation(20, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.MaxXMargin | EOViewLayout.HeightSizable);
        _nsView2.add(_nsTableView1);
        _nsTableView2.setSize(215, 734);
        _nsTableView2.setLocation(586, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView2.add(_nsTableView2);
        _nsSegmentedControl1.setSize(238, 24);
        _nsSegmentedControl1.setLocation(341, 733);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsSegmentedControl1, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView2.add(_nsSegmentedControl1);
        if (!(_nsBox9.getLayout() instanceof EOViewLayout)) { _nsBox9.setLayout(new EOViewLayout()); }
        _nsTextView2.setSize(769, 286);
        _nsTextView2.setLocation(16, 11);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox9.add(_nsTextView2);
        if (!(_nsBox8.getLayout() instanceof EOViewLayout)) { _nsBox8.setLayout(new EOViewLayout()); }
        _nsBox9.setSize(801, 308);
        _nsBox9.setLocation(2, 15);
        ((EOViewLayout)_nsBox8.getLayout()).setAutosizingMask(_nsBox9, EOViewLayout.MinYMargin);
        _nsBox8.add(_nsBox9);
        _nsBox8.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("History", true, "Lucida Grande", 11, Font.PLAIN));
        _nsTextView2.setEditable(true);
        _nsTextView2.setOpaque(true);
        _nsTextView2.setText("");
        _connect(_nsForm0, _nsTextView2, "nextFocusableComponent");
        _setFontForComponent(_eoFormCell2, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell2.setTitle("Race:");
        _eoFormCell2.setTitleWidth(43);
        _eoFormCell2.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell2.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _setFontForComponent(_eoFormCell1, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell1.setTitle("Sex:");
        _eoFormCell1.setTitleWidth(43);
        _eoFormCell1.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell1.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _setFontForComponent(_eoFormCell0, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell0.setTitle("Age:");
        _eoFormCell0.setTitleWidth(43);
        _eoFormCell0.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell0.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _eoFormCell0.setSize(1, 0);
        _eoFormCell0.setLocation(13, -2);
        _nsForm0.add(_eoFormCell0);
        _eoFormCell1.setSize(1, 0);
        _eoFormCell1.setLocation(13, -2);
        _nsForm0.add(_eoFormCell1);
        _eoFormCell2.setSize(1, 0);
        _eoFormCell2.setLocation(13, -2);
        _nsForm0.add(_eoFormCell2);
        _setFontForComponent(_nsForm0, "Lucida Grande", 13, Font.PLAIN);
        if (!(_nsBox7.getLayout() instanceof EOViewLayout)) { _nsBox7.setLayout(new EOViewLayout()); }
        _nsForm0.setSize(504, 82);
        _nsForm0.setLocation(24, 11);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsForm0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox7.add(_nsForm0);
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(801, 104);
        _nsBox7.setLocation(2, 15);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Patient Information", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsBox6.setSize(805, 121);
        _nsBox6.setLocation(8, 4);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsBox6);
        _nsBox8.setSize(805, 325);
        _nsBox8.setLocation(8, 129);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox8, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsBox8);
        _nsButton3.setSize(123, 26);
        _nsButton3.setLocation(443, 732);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton3);
        _nsCustomView0.setSize(302, 265);
        _nsCustomView0.setLocation(260, 464);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView0);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField7.setEditable(true);
        _nsTextField7.setOpaque(true);
        _nsTextField7.setText("");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(true);
        _nsTextField7.setEnabled(true);
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsTextField7.setSize(656, 22);
        _nsTextField7.setLocation(21, 179);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField7);
        _nsTextField0.setSize(743, 22);
        _nsTextField0.setLocation(21, 6);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField0);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(783, 35);
        _nsBox5.setLocation(2, 15);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Keywords", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsTextField3.setSize(743, 22);
        _nsTextField3.setLocation(21, 12);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField3);
        _nsTextField2.setSize(743, 22);
        _nsTextField2.setLocation(21, 44);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField2);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(783, 77);
        _nsBox3.setLocation(2, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Title / Alternative Title", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField1.setSize(656, 22);
        _nsTextField1.setLocation(21, 6);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsButton5.setSize(80, 26);
        _nsButton5.setLocation(691, 6);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton5);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(783, 35);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Reference Document", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Alternative Abstract\n\n");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Abstract\n\n");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Authors\n");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(true);
        _nsTextField3.setOpaque(true);
        _nsTextField3.setText("");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(true);
        _nsTextField3.setEnabled(true);
        _connect(_nsTextField3, _nsTextField2, "nextFocusableComponent");
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(true);
        _nsTextField2.setOpaque(true);
        _nsTextField2.setText("");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(true);
        _nsTextField2.setEnabled(true);
        _connect(_nsTextField2, _nsTableView0, "nextFocusableComponent");
        _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsSegmentedControl1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsSegmentedControl0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "remove", _nsButton1), ""));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "add", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_arrayController0") == null) {
            _connect(_arrayController0, _nsTableView0, "tableView");
        }

        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(true);
        _nsTextField1.setOpaque(true);
        _nsTextField1.setText("");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _connect(_nsTextField0, _nsTextField1, "nextFocusableComponent");
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(true);
        _nsTextField0.setOpaque(true);
        _nsTextField0.setText("");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(true);
        _nsTextField0.setEnabled(true);
        _connect(_nsTextView1, _nsTextField0, "nextFocusableComponent");
        _nsTextView1.setEditable(true);
        _nsTextView1.setOpaque(true);
        _nsTextView1.setText("");
        _connect(_nsTextView0, _nsTextView1, "nextFocusableComponent");
        _nsTextView0.setEditable(true);
        _nsTextView0.setOpaque(true);
        _nsTextView0.setText("");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _nsTextView0, "nextFocusableComponent");
        }

        _eoTableColumn5.setMinWidth(10);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(192);
        _eoTableColumn5.setWidth(192);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("address 2 ");
        if ((_eoTableColumn5.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn5.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn4.setMinWidth(10);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(90);
        _eoTableColumn4.setWidth(90);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("address 1");
        if ((_eoTableColumn4.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn4.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(100);
        _eoTableColumn3.setWidth(100);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Phone");
        if ((_eoTableColumn3.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn3.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn2.setMinWidth(40);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(129);
        _eoTableColumn2.setWidth(129);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("email");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn1.setMinWidth(55);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(136);
        _eoTableColumn1.setWidth(136);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Affiliation");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(98);
        _eoTableColumn0.setWidth(98);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Name");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _nsTableView0.table().addColumn(_eoTableColumn1);
            _nsTableView0.table().addColumn(_eoTableColumn2);
            _nsTableView0.table().addColumn(_eoTableColumn3);
            _nsTableView0.table().addColumn(_eoTableColumn4);
            _nsTableView0.table().addColumn(_eoTableColumn5);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(20);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(781, 91);
        _nsTableView0.setLocation(20, 112);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTableView0);
        _nsTextField4.setSize(129, 14);
        _nsTextField4.setLocation(33, 99);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField4);
        _nsTextField5.setSize(129, 14);
        _nsTextField5.setLocation(33, 219);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField5);
        _nsTextField6.setSize(129, 34);
        _nsTextField6.setLocation(33, 432);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField6);
        _nsBox0.setSize(787, 52);
        _nsBox0.setLocation(17, 711);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsBox2.setSize(787, 94);
        _nsBox2.setLocation(17, 0);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.WidthSizable | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsBox2);
        _nsBox4.setSize(787, 52);
        _nsBox4.setLocation(17, 655);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox4);
        _nsButton0.setSize(75, 26);
        _nsButton0.setLocation(730, 204);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsButton0);
        _nsButton1.setSize(75, 26);
        _nsButton1.setLocation(648, 204);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsButton1);
        _nsTextView0.setSize(781, 191);
        _nsTextView0.setLocation(20, 233);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsTextView0);
        _nsTextView1.setSize(781, 206);
        _nsTextView1.setLocation(20, 446);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextView1, EOViewLayout.MinXMargin | EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextView1);
        _nsTabView0.addTab("General", _nsView0);
        _nsTabView0.addTab("History", _nsView1);
        _nsTabView0.addTab("Images", _nsView2);
        _nsTabView0.addTab("Discussion", _nsView3);
        _nsTabView0.addTab("Quiz", _nsView4);
        if (!(_nsView5.getLayout() instanceof EOViewLayout)) { _nsView5.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(831, 814);
        _nsTabView0.setLocation(-5, 3);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView5.add(_nsTabView0);
        _nsButton2.setSize(75, 26);
        _nsButton2.setLocation(753, 818);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView5.add(_nsButton2);
        _nsButton6.setSize(88, 26);
        _nsButton6.setLocation(5, 813);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView5.add(_nsButton6);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView5.setSize(837, 849);
            _eoFrame0.setTitle(" MIRC XML Teaching File");
            _eoFrame0.setLocation(157, 299);
            _eoFrame0.setSize(837, 849);
        }
    }
}
