// _MIRCWebView_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, August 30, 2005 9:12:28 AM America/Denver

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MIRCWebView_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOView _webClipView0, _webDynamicScrollBarsView0, _webFrameView0, _webView0;
    javax.swing.JPanel _nsView0;

    public _MIRCWebView_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _webClipView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _webDynamicScrollBarsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _webFrameView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "webView")) != null)) {
            _webView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_webView0");
        } else {
            _webView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "WebView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_webView0") == null) {
            _connect(_owner(), _webView0, "webView");
        }
    }

    protected void _init() {
        super._init();
        if (!(_webDynamicScrollBarsView0.getLayout() instanceof EOViewLayout)) { _webDynamicScrollBarsView0.setLayout(new EOViewLayout()); }
        _webClipView0.setSize(811, 634);
        _webClipView0.setLocation(0, 0);
        ((EOViewLayout)_webDynamicScrollBarsView0.getLayout()).setAutosizingMask(_webClipView0, EOViewLayout.MinYMargin);
        _webDynamicScrollBarsView0.add(_webClipView0);
        if (!(_webFrameView0.getLayout() instanceof EOViewLayout)) { _webFrameView0.setLayout(new EOViewLayout()); }
        _webDynamicScrollBarsView0.setSize(811, 634);
        _webDynamicScrollBarsView0.setLocation(0, 0);
        ((EOViewLayout)_webFrameView0.getLayout()).setAutosizingMask(_webDynamicScrollBarsView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _webFrameView0.add(_webDynamicScrollBarsView0);

        if (_replacedObjects.objectForKey("_webView0") == null) {
            if (!(_webView0.getLayout() instanceof EOViewLayout)) { _webView0.setLayout(new EOViewLayout()); }
            _webFrameView0.setSize(811, 634);
            _webFrameView0.setLocation(0, 0);
            ((EOViewLayout)_webView0.getLayout()).setAutosizingMask(_webFrameView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _webView0.add(_webFrameView0);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _webView0.setSize(811, 634);
        _webView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_webView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_webView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(797, 622);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(223, 337);
            _eoFrame0.setSize(797, 622);
        }
    }
}
